version: "3.9"
services:
  web:
    build: .
    container_name: onion-forum
    expose:
      - "8080"
    environment:
      - FORUM_DB_PATH=/data/forum.db
      - PORT=8080
    volumes:
      - forum_data:/data
      # Uncomment the next line for live-reload style dev (requires restarting container to pick up python deps changes)
      # - ./:/app
    restart: unless-stopped
  tor:
    build:
      context: ./tor
    container_name: onion-forum-tor
    depends_on:
      - web
    volumes:
      - tor_data:/var/lib/tor
    environment:
      - TOR_HIDE=1
    restart: unless-stopped

volumes:
  forum_data:
  tor_data:
